# 前缀键（新：Ctrl + a）
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# 窗格导航（Vim 风格）
bind i select-pane -U
bind k select-pane -D
bind j select-pane -L
bind l select-pane -R

# 分屏
bind h split-window -h -c "#{pane_current_path}"  # 左右
bind v split-window -v -c "#{pane_current_path}"  # 上下

# 基础设置
set -g default-terminal "screen-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 100000

# 新窗口
bind c new-window -c "#{pane_current_path}"

# Vim 模式
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# 鼠标支持
set -g mouse on

# 重新加载
bind r source-file ~/.tmux.conf  display "配置已重载！"

# 状态栏
set -g status-style bg=colour235,fg=colour136
set -g window-status-current-style bg=colour136,fg=colour235
set -g status-left "#[fg=green]#S "
set -g status-right "#[fg=cyan]%Y-%m-%d %H:%M "
set -g status-interval 60

 


